name: Deploy to AWS S3

on:
  push:
    branches:
      - main  # どのブランチにプッシュした時動くか
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHubからコードを持ってる
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Node.jsをセットアップする
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # 3. 依存関係をインストール & ビルド
      - name: Install and Build
        run: |
          npm ci
          npm run build

      # 4. S3にアップロード
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1 # 東京リージョン
        run: |
          aws s3 sync dist/ s3://portfolio-bac7220 --delete

      # 5. CloudFrontのキャッシュをクリア（追記部分）
      - name: CloudFront Invalidation
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
        run: |
          aws cloudfront create-invalidation --distribution-id EA2PL6CJQ54HS --paths "/*"